[package]
name = "bfilters"
version = "0.1.3"
edition = "2021"
description = "Simple bloom filter implementation in Rust."
license-file = "LICENSE"
repository = "https://github.com/alexanderbakhmach/bloom-filter"

[dependencies]
fasthash = "0.4.0"